#version: "3.8"

services:
   nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
     - "8080:80"
    volumes:
     - ./web:/var/www/html
    secrets:
     - ssl-cert
     - ssl-key
  
   worpdress:
     build: requirements/wordpress/.
     container_name: wp-php
     volumes:
      - ./web:/var/www/html
     expose: 
      - 9000

   mariadb:
     build: requirements/mariadb/.
     container_name: mariadb
     volumes:
      - ./database:/var/lib/mysql

networks:
  inception:

secrets:
  ssl-cert:
    file: ../secrets/self-signed.crt
  ssl-key:
    file: ../secrets/self-signed.key